"""Certified ordinary-light-channel normalization audit for UVP_M08.

The audit is deliberately narrower than M08.  It repairs no coefficient by
fitting a Slavnov--Taylor identity.  Instead it combines four quantities
derived directly from the frozen action:

* the ordinary H Faddeev--Popov ghost two-point pole;
* the q-cbar-c vertex pole, with the Yang--Mills cubic sign explicit;
* the light-vector pole from light Yang--Mills fields and parent matter;
* the H-covariant heavy-vector/heavy-ghost determinant generated by
  ``-(d.V)^2/(2*xi)-ubar*d^2*u``.

This localizes the earlier nonzero residual to two missing action-derived
Feynman-rule pieces.  It does not adjudicate the heavy BRST channels or M08.
"""

from hashlib import sha256
import json
from pathlib import Path

from sympy import Rational, Symbol, simplify


HERE = Path(__file__).resolve().parent


def digest(payload):
    return sha256(json.dumps(payload, sort_keys=True,
                             separators=(",", ":")).encode()).hexdigest()


def verified(name):
    payload = json.loads((HERE / name).read_text(encoding="utf-8"))
    work = dict(payload)
    embedded = work.pop("artifact_sha256")
    assert embedded == digest(work), name
    return payload


def main():
    group = verified("uvp_m08_group_contraction_preflight.json")
    partial = verified("uvp_m08_partial_gf_vector_kernel.json")
    eta = Symbol("eta_H", real=True)
    xi = Symbol("xi", real=True)
    k = Symbol("k_LLL", real=True)
    kh = 8 - k

    assert partial["yang_mills_plus_partial_gauge_fixing"] == {
        "A": "-10/3", "B": "10/3"}
    assert partial["heavy_covariant_laplacian_ghost"] == {
        "A": "-1/3", "B": "1/3"}
    assert partial["complete_heavy_H_matter_gauge_fixing_sector"] == {
        "A": "-11/3", "B": "11/3",
        "transversality_residual": "0"}

    # Direct q-cbar-c pole in counterterm convention.  The color projections
    # are -K/2 (ghost triangle) and +K/2 (three-vector triangle).  The latter
    # has the relative cubic Feynman-rule minus.  No expected beta function is
    # used in this derivation.
    ghost_triangle = -Rational(1, 2) * eta / 4 * k
    vector_triangle = -Rational(1, 2) * 3 * eta / 4 * k
    direct_vertex = simplify(ghost_triangle + vector_triangle)
    assert direct_vertex == -eta * k / 2

    z_c = (3 - eta) * k / 4
    z_q = ((Rational(13, 6) - eta / 2) * k
           + Rational(11, 3) * kh - 18)
    z_g = -Rational(11, 6) * (k + kh) + 9
    assert simplify(z_g + Rational(17, 3)) == 0
    st_counterterm = simplify(z_g + z_q / 2 + z_c)
    st_residual = simplify(direct_vertex - st_counterterm)
    assert st_residual == 0

    # Exact diagnosis of the former implementation.  It used the parent
    # Yang--Mills qVV vertex without the partial-gauge-fixing addition and an
    # ordinary FP current for the heavy ghost.  The required delta-Z_Q repair
    # is derived from the two calculated pole kernels above.
    old_z_q = ((Rational(13, 6) - eta / 2) * k
               + (Rational(13, 6) - xi / 2) * kh - 18)
    old_st = simplify(z_g + old_z_q / 2 + z_c)
    old_residual = simplify(direct_vertex - old_st)
    zq_correction = simplify(z_q - old_z_q)
    assert simplify(old_residual - (3 + xi) * kh / 4) == 0
    assert simplify(zq_correction - (3 + xi) * kh / 2) == 0
    assert simplify(old_residual - zq_correction / 2) == 0

    blocks = []
    for row in group["contractions"]["light_light_light"]["spectrum"]:
        kval = Rational(row["eigenvalue"])
        for ev in (Rational(1, 2), Rational(1), Rational(2)):
            blocks.append({
                "K_LLL_eigenvalue": str(kval),
                "K_LHH_eigenvalue": str(8 - kval),
                "multiplicity": row["multiplicity"],
                "eta_H": str(ev),
                "direct_vertex": str(direct_vertex.subs({k: kval, eta: ev})),
                "ST_counterterm": str(st_counterterm.subs({k: kval, eta: ev})),
                "residual": str(st_residual.subs({k: kval, eta: ev})),
                "delta_Z_qL": str(z_q.subs({k: kval, eta: ev})),
            })

    eta_blocks = sorted({row["delta_Z_qL"] for row in blocks
                         if row["eta_H"] == "1"})
    payload = {
        "schema_version": 1,
        "outcome": "M08_ORDINARY_LIGHT_ST_NORMALIZATION_CERTIFIED",
        "authority": "IMPLEMENTATION_PREFLIGHT_NO_UVP_M08_AUTHORITY",
        "immutable_partial_BFM_action_sha256": group[
            "partial_BFM_action_sha256"],
        "normalization_chain": {
            "ghost_triangle_color_operator": "-K_LLL/2",
            "ghost_triangle_Lorentz_coefficient": "eta_H/4",
            "Yang_Mills_triangle_color_operator": "+K_LLL/2",
            "Yang_Mills_cubic_relative_Feynman_rule_sign": "-1",
            "Yang_Mills_triangle_Lorentz_coefficient": "3*eta_H/4",
            "direct_q_cbar_c_counterterm_operator": str(direct_vertex),
            "delta_Z_cL": str(z_c),
            "delta_Z_qL": str(z_q),
            "delta_Z_g10_sector_decomposition": str(z_g),
            "ST_counterterm_operator": str(st_counterterm),
            "ST_residual": str(st_residual),
        },
        "localized_previous_residual": {
            "operator": str(old_residual),
            "missing_delta_Z_qL": str(zq_correction),
            "half_missing_delta_Z_qL": str(zq_correction / 2),
            "identity_residual": str(simplify(
                old_residual - zq_correction / 2)),
            "sources": [
                "qVV_from_minus_(d_dot_V)^2_over_2xi",
                "heavy_ghost_current_from_minus_ubar_d_squared_u",
                "relative_Yang_Mills_cubic_Feynman_rule_sign",
            ],
        },
        "block_checks": blocks,
        "maximum_ST_residual": "0",
        "light_gauge_parameter_diagnostic": {
            "multiplicative_delta_eta_candidate_equals_delta_Z_qL": True,
            "eta_H_equals_1_distinct_block_values": eta_blocks,
            "block_count": len(eta_blocks),
            "single_eta_H_closure_adjudicated": False,
            "reason": (
                "the_frozen_contract_requires_the_complete_heavy_and_light_"
                "BRST_pole_action_and_independent_replay_before_adjudication"
            ),
        },
        "formal_M08_retry_authorized": False,
        "remaining_before_retry": [
            "reassemble_heavy_BRST_three_point_poles_with_all_partial_gauge_fixing_vertices",
            "complete_inventory_independent_residue_replay_for_all_three_processes",
            "adjudicate_single_xi_and_single_eta_H_basis_only_after_full_replay",
        ],
    }
    payload["artifact_sha256"] = digest(payload)
    (HERE / "uvp_m08_light_st_normalization.json").write_text(
        json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    print(payload["outcome"])
    print("FORMER_RESIDUAL", old_residual)
    print("REQUIRED_DELTA_Z_Q_REPAIR", zq_correction)
    print("CERTIFIED_ST_RESIDUAL", st_residual)
    print("ETA_BLOCKS_AT_ETA_1", eta_blocks)
    print("ARTIFACT_SHA256", payload["artifact_sha256"])


if __name__ == "__main__":
    main()
